title: "Hsuan-Ting Lai"
email: "htlai@e-dream.tw"
description: "Ph.D. student in Geophysics at National Central University"
url: "https://htwho.github.io"
baseurl: ""
markdown: kramdown
permalink: pretty
orcid_url: "https://orcid.org/0000-0001-9049-7580"
github_url: "https://github.com/htwho"
website_url: "https://htwho.github.io/"
researchgate_url: "https://www.researchgate.net/profile/Hsuan-Ting-Lai"
scholar_url: "https://scholar.google.com/citations?user=9P2kYnIAAAAJ&hl=zh-TW&oi=ao"
x_url: "https://x.com/htwho20"

collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
